type Product = {
  _id: string;
  title: string;
  description: string;
  oldPrice: number;
  price: number;
  brand: string;
  image: string;
  isNew: boolean;
  category: string;
  quantity: number;
  made: string;
};

export const ProductData: Product[] = [
  {
    _id: "1",
    title: "Gold Plated Hoop Earrings",
    description: "Elegant gold plated hoop earrings for everyday wear.",
    oldPrice: 35.99,
    price: 25.99,
    brand: "FashionJewels",
    image: "https://picsum.photos//id/789/780/420",
    isNew: false,
    category: "Earrings",
    quantity: 1,
    made: "handMade",
  },
  {
    _id: "2",
    title: "Silver Diamond Necklace",
    description: "Stunning silver necklace with a sparkling diamond pendant.",
    oldPrice: 89.99,
    price: 69.99,
    brand: "LuxuryGems",
    image: "https://picsum.photos//id/3/780/420",
    isNew: true,
    category: "Necklaces",
    quantity: 1,
    made: "handMade",
  },
  {
    _id: "3",
    title: "Rose Gold Bangle Bracelet",
    description: "Chic rose gold bangle bracelet to complement any outfit.",
    oldPrice: 45.99,
    price: 39.99,
    brand: "TrendyAccessories",
    image: "https://picsum.photos//id/1/780/420",
    isNew: true,
    category: "Bracelets",
    quantity: 1,
    made: "handMade",
  },

  {
    _id: "20",
    title: "Sapphire and Diamond Ring",
    description: "Exquisite sapphire and diamond ring for a touch of luxury.",
    oldPrice: 299.99,
    price: 249.99,
    brand: "GlamourGems",
    image: "https://picsum.photos//id/543/780/420",
    isNew: false,
    category: "Rings",
    quantity: 1,
    made: "handMade",
  },
  {
    _id: "21",
    title: "Pearl Stud Earrings",
    description: "Classic pearl stud earrings that never go out of style.",
    oldPrice: 19.99,
    price: 14.99,
    brand: "TimelessPearls",
    image: "https://picsum.photos//id/4/780/420",
    isNew: true,
    category: "Earrings",
    quantity: 1,
    made: "handMade",
  },
  {
    _id: "22",
    title: "Diamond Tennis Bracelet",
    description:
      "Elegant diamond tennis bracelet for a touch of sophistication.",
    oldPrice: 199.99,
    price: 179.99,
    brand: "LuxuryGems",
    image: "https://picsum.photos//id/32/780/420",
    isNew: false,
    category: "Bracelets",
    quantity: 1,
    made: "handMade",
  },
  {
    _id: "23",
    title: "Emerald Pendant Necklace",
    description: "Gorgeous emerald pendant necklace that catches the eye.",
    oldPrice: 79.99,
    price: 59.99,
    brand: "GlamourGems",
    image: "https://picsum.photos//id/8/780/420",
    isNew: true,
    category: "Necklaces",
    quantity: 1,
    made: "handMade",
  },
  {
    _id: "24",
    title: "Silver and Turquoise Ring",
    description: "Stunning silver ring with a turquoise gemstone.",
    oldPrice: 34.99,
    price: 29.99,
    brand: "TrendyAccessories",
    image: "https://picsum.photos//id/456/780/420",
    isNew: true,
    category: "Rings",
    quantity: 1,
    made: "handMade",
  },
  {
    _id: "25",
    title: "Charm Bracelet",
    description: "Adorable charm bracelet with various cute charms.",
    oldPrice: 27.99,
    price: 19.99,
    brand: "FashionJewels",
    image: "https://picsum.photos//id/789/780/420",
    isNew: false,
    category: "Bracelets",
    quantity: 1,
    made: "handMade",
  },
  {
    _id: "26",
    title: "Diamond Cluster Earrings",
    description: "Glamorous diamond cluster earrings for special occasions.",
    oldPrice: 89.99,
    price: 69.99,
    brand: "LuxuryGems",
    image: "https://picsum.photos//id/321/780/420",
    isNew: true,
    category: "Earrings",
    quantity: 1,
    made: "manafacture",
  },
  {
    _id: "27",
    title: "Ruby and Diamond Ring",
    description: "Exquisite ruby and diamond ring that commands attention.",
    oldPrice: 249.99,
    price: 199.99,
    brand: "GlamourGems",
    image: "https://picsum.photos//id/12/780/420",
    isNew: false,
    category: "Rings",
    quantity: 1,
    made: "handMade",
  },
  {
    _id: "28",
    title: "Gold Chain Necklace",
    description: "Simple and elegant gold chain necklace for everyday wear.",
    oldPrice: 39.99,
    price: 29.99,
    brand: "TimelessPearls",
    image: "https://picsum.photos//id/21/780/420",
    isNew: false,
    category: "Necklaces",
    quantity: 1,
    made: "handMade",
  },
  {
    _id: "29",
    title: "Cubic Zirconia Stud Earrings",
    description: "Affordable yet stunning cubic zirconia stud earrings.",
    oldPrice: 12.99,
    price: 9.99,
    brand: "FashionJewels",
    image: "https://picsum.photos//id/42/780/420",
    isNew: true,
    category: "Earrings",
    quantity: 1,
    made: "manafacture",
  },
  {
    _id: "30",
    title: "Rose Gold Anklet",
    description: "Trendy rose gold anklet to add some flair to your style.",
    oldPrice: 22.99,
    price: 18.99,
    brand: "TrendyAccessories",
    image: "https://picsum.photos//id/12/780/420",
    isNew: true,
    category: "Anklets",
    quantity: 1,
    made: "manafacture",
  },
];
