import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./styles/globals.css";
import type { Metadata } from "next";
import { Open_Sans, Abril_Fatface } from "next/font/google";

const open_sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`homebg m-3 ${open_sans.variable} font-sans`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
