import Navbar from "./components/Navbar";
import "./styles/globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

const open_sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-montserrat",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` bg-transparent m-3 ${open_sans.variable} font-sans`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
